### ISSUE TITLE
Document or reference for implementation

### ISSUE THREAD

**Issue by milad-ahmadi** [ooterness/DualFisheye#1]
Hello,
Is there a reference or document to understanding the algorithm used in this implementation? Please, if possible, publish the resource or document.
Thanks

**Comment by ooterness** [comment]
The main "inspiration" for a lot of this is from [Paul Bourke](http://paulbourke.net/dome/dualfish2sphere/).  Beyond that, it's all just ad hoc.  I'd just try something and tweak it until it worked well enough with the test images I had available.

The core rendering algorithm works backwards from each pixel in the output image.  It's roughly analogous to ray-tracing:
- Map the output pixel to a point in 3D space.  Convert that to an XYZ unit vector.
- For each source image, rotate the unit vector into camera space.
- Remap that to UV space in the 2D source image.  I assume a perfectly linear ["equidistant"](https://en.wikipedia.org/wiki/Fisheye_lens#Mapping_function) function for the lens. 
- If that UV coordinate is inside the image, assign it a weight according to how close to the center it is.
- Output RGB value is a weighted average of all applicable source(s).  IIRC it's just nearest-neighbor sampling.

The auto-tuning system is a generic minimizer from SciPy.  It's blindly tweaking all the lens parameters, looking at MSE between overlapping segments, with an additional reward/penalty heuristic for maximizing overlap and minimizing coverage gaps.  Otherwise it just converges on a useless local minimum where the outputs don't overlap, even if it's clear they could be aligned.  Doing that with downsampled source images, and then repeating at progressively higher input resolution massively speeds up the process and helps keep it from getting stuck in local minima.

In terms of ongoing improvements if anyone has time or interest:
- Vignetting compensation.  Most fisheye lenses get darker as you get near the edge.
- Lens distortion, and support for other lens mappings.  (No lens is perfectly linear, some drastically so.)
